name: main

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 12 */10 * *'
jobs:
  run-composer-bin:
    runs-on: ubuntu-latest
    steps:
      - name : composer require and issue cert
        shell: bash
        run : |
          php -v
          mkdir -p sample/bin
          cd sample
          composer require takuya/php-letencrypt-acme-dns
          cp vendor/takuya/php-letencrypt-acme-dns/bin/request-issue.php .
          export LE_CLOUDFLARE_TOKEN=${{ secrets.LE_CLOUDFLARE_TOKEN1 }}
          export LE_BASE_DOMAIN=${{ secrets.LE_BASE_DOMAIN1 }}
          php bin/request-issue.php sample.$LE_BASE_DOMAIN

