name: main

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 11 */5 * *'
jobs:
  run-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name : env_vars
        run:
          echo expected variables
          echo LE_CLOUDFLARE_TOKEN1=6qv...zFc from github action secret
          echo LE_CLOUDFLARE_TOKEN2=K8Q...Pbh from github action secret
          echo LE_BASE_DOMAIN1=.biz
          echo LE_BASE_DOMAIN2=.com
          echo imported variables.
          echo LE_CLOUDFLARE_TOKEN1=${{ secrets.LE_CLOUDFLARE_TOKEN1 }}
          echo LE_CLOUDFLARE_TOKEN2=${{ secrets.LE_CLOUDFLARE_TOKEN2 }}
          echo LE_BASE_DOMAIN1=${{ secrets.LE_BASE_DOMAIN1 }}
          echo LE_BASE_DOMAIN2=${{ secrets.LE_BASE_DOMAIN2 }}
      - name : composer install
        shell: bash
        run : |
          php -v
          composer install  -q --no-ansi --no-interaction --no-progress
      - name : UnitTest
        shell: bash
        run : |
          vendor/bin/phpunit --filter Unit
      - name : log
        shell: bash
        run : |
          date -I > last-tested.txt
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update tested date.
